### PR TITLE
More restructuring...

### PR DESCRIPTION
**Pull request by TimHenkelmann**
Some more restructuring, deleted few typos, added readme for dbpedia and created global package.json file

### CODE REVIEW

**Review by ShilpaGhanashyamGore — APPROVED** [review]
Looks good.

**Comment by sacdallago** [comment]
I guess the `dbpedia/dbPedia_Composers.js` wasn't supposed to be here?

**Comment by TimHenkelmann** [comment]
@sacdallago Uhm, what do you mean by that? This PR actually contains a few changes as mentioned above

**Comment by ShilpaGhanashyamGore** [comment]
@sacdallago :dbpedia/dbPedia_Composers.js  is the script to scrape dbpedia composers .It should be in the same folder as other dbpedia scripts .I think it is in correct directory.

**Comment by sacdallago** [comment]
@TimHenkelmann @ShilpaGhanashyamGore sorry both :D I thought it was a `.json` file.. I'm gonna hide now?

**Pull request merged**
