### PR TITLE
Entities imslp fix

### PR DESCRIPTION
**Pull request by sacdallago**
- Updated submodule
- Script now performs much faster (5 minutes vs 3h)
- Removed `sync:force` instances from code

### CODE REVIEW

**Review by kordianbruck — APPROVED** [review]
Cool - lets get this in

**Comment by TimHenkelmann** [comment]
Hey @sacdallago , could you fix the conflicts in imslp.js? Since it's your code, I do not want to (evidently) break anything :D

**Comment by kordianbruck** [comment]
@TimHenkelmann chris is out, so if you can fix it - that would be great.

**Comment by TimHenkelmann** [comment]
I'll give it a try then!

**Comment by kordianbruck** [comment]
Splendid! <3

**Pull request merged**
