### PR TITLE
fixed travis file

### PR DESCRIPTION
**Pull request by TimHenkelmann**
Fixed indention and added new line for travis file

### CODE REVIEW

**Review by ShilpaGhanashyamGore — APPROVED** [review]
Fixing the indentation issue .

**Comment by sacdallago** [comment]
The build is failing, because the submodule is imported via ssh and not http. It's expected behaviour! You probably want to adapt your travis file a bit to change the ssh to http on the fly, as explained [here](http://stackoverflow.com/a/24600210/5708679)

**Review by ShilpaGhanashyamGore — APPROVED** [review]
Okay!

**Comment by kordianbruck** [comment]
@ShilpaGhanashyamGore how can you say that a PR is okay when the build fails?

**Comment by ShilpaGhanashyamGore** [comment]
@kordianbruck  We are fixing the CI failures by adapting the travis file . CI is triggered only after we merge the changes This is the latest result we got - https://travis-ci.org/MusicConnectionMachine/StructuredData
Changing indentation and changing the SSH to git repo url + handling of git submodule has solved the CI failures .
Am I missing something ?Let me know. Thanks !

**Comment by kordianbruck** [comment]
No, everything is fine - proceed :+1:

**Pull request merged**
